# Generated by Django 2.1.1 on 2018-10-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('uid', models.CharField(blank=True, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('uPassword', models.CharField(max_length=15)),
                ('uEamil', models.CharField(max_length=25)),
                ('uPhone', models.CharField(max_length=11)),
                ('uRegisterDate', models.DateTimeField()),
            ],
        ),
    ]
