# Generated by Django 2.1.1 on 2018-10-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='uSex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uRegisterDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
