# Generated by Django 2.1.1 on 2018-10-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20181002_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='uPhone',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='uid',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='uName',
            field=models.CharField(blank=True, max_length=128, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uEamil',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uPassword',
            field=models.CharField(max_length=256),
        ),
    ]
